### ISSUE TITLE
missing LICENSE file

### ISSUE THREAD

**Issue by binarycrusader** [softdorothy/glider_pro#2]
glider_pro is missing a LICENSE file, unlike the other glider repositories.

**Comment by softdorothy** [comment]
I didn't know which one to use. If you want to use the sources give me a holler and we'll figure something out.

**Comment by d235j** [comment]
I'd like to see one just because it would make it easier for others to contribute — technically, no license means "Copyright — All Rights Reserved" and that "nobody else may reproduce, distribute, or create derivative works from your work."

http://choosealicense.com should be helpful here.

**Comment by mbeards** [comment]
Agreed that a LICENSE file is really important to add. Ideally one of the more common licenses (GPL, MIT, BSD, etc).

Personally I'd like to tinker with this, but am unable to publish patches without a license

**Comment by softdorothy** [comment]
Thanks for the link — I went with what I think is the GPL license. (I'm new at licenses.)

**Comment by d235j** [comment]
@softdorothy: that's the AGPL license; If you want to use the GPL, I instead recommend the regular GPL, either version 2.0 or later, or version 3.0, depending on what your intent is.

The AGPL is intended for software where server-side scripts are used and requires that the end-user be able to obtain the source code even if the binary code isn't being provided to them directly. I don't think it makes sense here.

You should place a file named COPYING in the root of the repository, containing the text of the license. Also you should modify the README to indicate this.
There's plenty of information at https://opensource.org/licenses/gpl-license, at the very bottom of the text of the licenses, on how exactly to do this. (You don't need to put this in every source file but some projects do if things are under multiple licenses for better clarity. I don't think it's necessary here.) Note that the GPLv2 has the optional text for "or later".

**Comment by softdorothy** [comment]
Derp. I'll have to do more digging around then. Is there a sample project that comes to mind that has a GPL (version 2.0 or 3.0, I don't care) license I can pull and move over?

**Comment by yoasif** [comment]
Example: https://github.com/textmate/textmate/blob/master/LICENSE

**Comment by d235j** [comment]
Yes, that's a good example (naming the file COPYING is acceptable as well). Also see https://github.com/textmate/textmate#legal — feel free to replace the text with the GPLv2 and change the "3" to "2" in there if that's what you'd prefer.

**Comment by d235j** [comment]
@softdorothy: the COPYING/LICENSE file needs to contain the _full text_ of the license. You can grab a copy of the GPLv2 in Markdown at https://github.com/nevir/readable-licenses/blob/master/markdown/GPLv2-LICENSE.md.

The README file should contain a License or Legal section specifying that the code is under the license, as can be seen at https://github.com/textmate/textmate#legal.

**Comment by softdorothy** [comment]
Done.

**Comment by d235j** [comment]
Looks good, though minor recommended change (if you want to keep it GPLv2 or later):

Change the text in the README to read as follows:

```
## Legal
The source for Glider PRO is released under the GNU General Public License 2 as published by the Free Software Foundation, or any later version. A copy of the license is provided at [GPLv2-License.md](GPLv2-License.md).
```

**Comment by kaixinzheng** [comment]
Hi John，I heard that you are mac Preview application programmer, I love the original Preview icon, https://www.quora.com/Who-is-the-kid-in-the-Preview-app-on-Mac-OS-X-and-where-is-he 

Could you tell me some story about this icon and send me the photo?
