### ISSUE TITLE
House editor source code missing

### ISSUE THREAD

**Issue by d235j** [softdorothy/glider_pro#7]
The source code to the house editor is not in this release. While I'm aware it was never ported to OS X, it would be very nice to have (and improve)!

**Comment by softdorothy** [comment]
Is it missing? In Glider PRO it was integrated into the Glider app — it was not a separate app.

**Comment by d235j** [comment]
Hm I think you're right — I wasn't looking hard enough.
Though how was is disabled in the Mac OS X build?

**Comment by softdorothy** [comment]
As I recall, there were a lot of dialog hooks that were very difficult to do in Carbon and would require rewriting many of them. And the editor was loaded with dialogs — for editing object properties, room properties, etc. I'm not sure how it was disabled. Perhaps by simply removing the menu item that switched to the editor.

There may nonetheless be more recent sources that I simply haven't found on my various hard drives. If I find something more recent I will certainly update the repository.

**Comment by d235j** [comment]
@softdorothy from more digging it seems like the OS X specific changes are not here... can you check if you have any source or project files for that build? It probably would make things easier regarding making a working Intel Carbon build. (I remember you told me in an email some years ago about endianness issues — I wrote some endian-conversion code, but I'm running into weird crashes in QuickDraw with CopyRect that are not being easy to debug.)

**Comment by softdorothy** [comment]
Yeah, there were endian issued reading the house files of course. I'll see what I can find....

**Comment by d235j** [comment]
@softdorothy additionally, any chance you still have the source code to the WDEF resources (and any other code resources)? It seems there are two in use by the house editor for the windoids.

EDIT: hmm never mind — I found it at http://macgui.com/downloads/?file_id=17924 — it looks like it was a freeware windoid that came with source code. I assume you didn't make any mods to it?

**Comment by d235j** [comment]
@softdorothy however it seems you used a custom CDEF in the Tools window in the House editor? More information for this (or source code if there is any) would be nice.

**Comment by softdorothy** [comment]
No idea. Leave off the custom CDEF and see what doesn't work. :-)

**Comment by d235j** [comment]
Based on the code, the custom CDEF is used to render the tools palette in the House editor — which is a fairly critical component of it. I'll try this but chances are that will give us a blank windoid. Source code to it would make porting it easier (as there would be no need to reverse-engineer the function!)
Any luck regarding newer code for the OS X port? I've had to do many changes (regarding SetPort/SetGWorld and CopyBits) to get it to run without crashing on OS X and it would not surprise me if these changes were also necessary in the PPC port. In hindsight the endian issues were fairly simple (though my "solution" is to byteswap the entire house in RAM on load, which is not particularly fast).
